# Site settings
author: Joey Luis Echevarria
title: 
header-img: img/home-bg.png
email: jechevarria719@gmail.com
copyright_name: Joey Luis Echevarria
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Joey0719

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
